import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import axios from 'axios';

export async function getServerSideProps(context) {
  const { txHash } = context.query;
  const response = await axios.get(`${process.env.BASE_URL}/api/v1/txs/${txHash}`); // so we need to set up an ENV var to get this off hardcoded dev server
  if (response.status === 200) {
  return {
    props: {
      response: response.data.tx,
    },
  }
} else {
  return {
    props: {response: response.status}
  }
}
}

export default function TxHash(props) {
  return (
    <div>
      <Head>
        <title>CNFT Transactions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <div>
            <h1>CNFT Transactions</h1>
            {props.response.output_amount && 
              props.response.output_amount.map((x, i) => 
              <>
              <p>{x.unit === 'lovelace' ? 'Ada' : x.unit} {x.unit === 'lovelace' ? x.quantity / 1_000_000 : x.quantity}</p>
              </>
              )
            }
          </div>        
        </div>
      </main>
  

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
