import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import axios from 'axios';
import { useState } from 'react';
import { useRouter } from 'next/router'

export async function getServerSideProps(context) {
  const { txHash } = context.query;
  const response = await axios.get(`http://localhost:3000/api/v1/txs/${txHash}`);
  return {
    props: {response: response.data}, // will be passed to the page component as props
  }
}

export default function TxHash(props) {
  const router = useRouter()
  console.log(props);
  const { TxHash } = router.query

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <div>
            <h1>CNFT Transactions</h1>
          </div>        
        </div>
      </main>
  

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
