import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { useState } from 'react';

export default function Home() {
  const [id, setId] = useState('');
  const [policyId, setPolicyId] = useState('');
  const [unsigE, setUnsigE] = useState([]);

  const handleValueChange = (stateToChange, value) => {
    if(stateToChange === 'policyId') {
      setPolicyId(value);
    }
    if( stateToChange === 'id')
    setId(value)
  };
 const handleTestLog = async (id, policyId) => {
    try {
      const response = await axios.get(`/api/v1/history/${policyId}?id=${id}`);
      setUnsigE(response.data);
    } catch (error) {
      console.error(error);
  }
 }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <div>
            <h1>CNFT Transactions</h1>
          </div>
          <div>
        {unsigE?.lasttxs?.length > 1 && 
            <Image src={`https://ipfs.io/ipfs/${unsigE.assetImage.replace('ipfs://', '')}`} alt={'asset image'} width={500} height={500}/>
          } 
        </div>
          <div>
          <input value={policyId} onChange={(e) => handleValueChange('policyId', e.target.value)}></input>
          <input value={id} onChange={(e) => handleValueChange('id', e.target.value)}></input>
          <button onClick={() => handleTestLog(id, policyId)}>Search</button>
          </div>  
          {unsigE?.lasttxs?.length > 1 && 
            unsigE?.lasttxs.map((unsig,i) => {
              if (i < 4){
              return(
                <div key={unsig}>
                <h4>tx hash</h4>
                <p>{unsig}</p>
                </div>
              )}
            })
          } 
        </div>
        <div>
        {unsigE?.lasttxs?.length > 1 && 
            unsigE?.adaAmounts.map((amount,i) => {
              return(
                <div key={i}>
                <h4>{i > 0  && 'then '}sold for</h4>
                <p>{amount}</p>
                </div>
              )
            })
          } 
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
